spring:
  application:
    name: service-test
  datasource:
    url: jdbc:mysql://localhost:3306/health?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      time-to-live: 1m
  data:
    redis:
      host: localhost
      port: 6379
      # Redis 连接池配置
      lettuce:
        pool:
          max-active: 8       # 连接池最大活跃连接数
          max-idle: 8         # 连接池最大空闲连接数
          min-idle: 0         # 连接池最小空闲连接数
          max-wait: -1ms      # 获取连接最大等待时间(负值表示无限等待)
          time-between-eviction-runs: -1ms  # 空闲连接清理线程运行间隔(负值表示不运行清理线程)
server:
  port: 8005
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.pojo
logging:
  level:
    # MyBatis日志
    com.example.dao: DEBUG


jwt:
  secret: qqp74374032742374hfdsfksdjfksdfsd78dsadhasnasdnasdnjkasndksankdlasdnmaskldnmaskdnkasdnmaskldl
  expiration: 3600
tocken:
  time:10
